/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import ISysInstallerCallback;
interface OHOS.SysInstaller.ISysInstaller {
    void SysInstallerInit([in] String taskId, [in] boolean bStreamUpgrade);
    [oneway] void StartUpdatePackageZip([in] String taskId, [in] String pkgPath);
    void StartStreamUpdate();
    void StopStreamUpdate();
    void ProcessStreamData([in] List<unsigned char> buffer, [in] unsigned int size);
    [oneway] void SetUpdateCallback([in] String taskId, [in] ISysInstallerCallback updateCallback);
    [oneway] void GetUpdateStatus([in] String taskId);
    void StartUpdateParaZip([in] String taskId, [in] String pkgPath, [in] String location, [in] String cfgDir);
    void StartDeleteParaZip([in] String taskId, [in] String location, [in] String cfgDir);
    void AccDecompressAndVerifyPkg([in] String taskId, [in] String srcPath, [in] String dstPath, [in] unsigned int type);
    void AccDeleteDir([in] String taskId, [in] String dstPath);
    void CancelUpdateVabPackageZip();
    [oneway] void StartUpdateVabPackageZip([in] String taskId, [in] List<String> pkgPath);
    [oneway] void StartVabMerge([in] String taskId);
    [oneway] void EnableVabCheckpoint();
    [oneway] void AbortVabActiveSnapshot();
    [oneway] void ClearVabMetadataAndCow();
    void MergeRollbackReasonFile();
    void GetMetadataUpdateStatus([out] int metadataStatus);
    void CreateVabSnapshotCowImg([in] Map<String, unsigned long> partitionInfo);
    void GetUpdateResult([in] String taskId, [in] String taskType, [in] String resultType, [out] String updateResult);
}