/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package OHOS;

enum UpdateStatus {
    UPDATE_STATE_INIT = 0,
    UPDATE_STATE_ONGOING,
    UPDATE_STATE_FAILED,
    UPDATE_STATE_SUCCESSFUL,
    UPDATE_STATE_CANCEL,
    UPDATE_STATE_BUSY,
    UPDATE_STATE_MAX,
};

enum InstallMode {
    FEATURE_INSTALL = 0,
    REGULAR_OTA,
    STREAM_OTA,
    AB_REGULAR_OTA,
    AB_STREAM_OTA,
    VAB_REGULAR_OTA,
    VAB_STREAM_OTA,
};

enum RebootStatus {
    NOT_REBOOT = 0,
    REBOOTED,
};

enum CloudRomInstallStatus {
    ERROR = -1,
    INIT = 0,
    INSTALLING = 10,
    UNZIP_PKG_SUCCESS,
    RESTORE_PKG_SUCCESS,
    WAIT_REBOOT_THEN_INSTALL,
    WAIT_UPGRADE_THEN_INSTALL,
    INSTALL_FAIL,
    INSTALL_SUCCESS,
    UNINSTALLING = 30,
    WAIT_REBOOT_THEN_UNINSTALL,
    UNINSTALL_FAIL,
    UNINSTALL_SUCCESS,
};

enum VabActiveMode {
    VAB_ACTIVE_HOTA = 0,
    VAB_ACTIVE_PATCH,
};

struct FeatureInfo {
    boolean isNeedReboot;
    String featureName;
    String version;
    String path;
};

struct ErrorInfo {
    int errorCode;
    String errorMsg;
};

struct FeatureStatus {
    String featureName;
    String version;
    String installPath;
    CloudRomInstallStatus status;
    ErrorInfo errorInfo;
    unsigned int featureType;
};
